-- 코드를 입력하세요
SELECT
    F2.INGREDIENT_TYPE,
    SUM(F1.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F1
JOIN ICECREAM_INFO AS F2 ON F1.FLAVOR = F2.FLAVOR
GROUP BY F2.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER